import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#002328',
        'surface-tint': '#afc8f0',
        'on-primary-fixed-variant': '#2f486a',
        'on-secondary-fixed': '#001d36',
        'on-secondary-container': '#9eb7d8',
        'on-primary-container': '#6f88ad',
        'primary-fixed': '#d4e3ff',
        'on-secondary': '#17324d',
        'on-surface': '#d6e4f9',
        'tertiary-fixed-dim': '#00daf3',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#2f4865',
        'secondary': '#afc9ea',
        'on-surface-variant': '#c4c6cf',
        'surface-container-low': '#0f1c2c',
        'tertiary': '#00daf3',
        'secondary-fixed-dim': '#afc9ea',
        'primary-container': '#001f3f',
        'error-container': '#93000a',
        'primary': '#afc8f0',
        'error': '#ffb4ab',
        'surface-container-highest': '#283646',
        'surface-container': '#132030',
        'secondary-container': '#2f4865',
        'outline': '#8e9198',
        'on-tertiary': '#00363d',
        'on-tertiary-fixed': '#001f24',
        'on-primary-fixed': '#001c3a',
        'tertiary-fixed': '#9cf0ff',
        'surface-variant': '#283646',
        'on-tertiary-fixed-variant': '#004f58',
        'secondary-fixed': '#d1e4ff',
        'surface-bright': '#2d3a4a',
        'surface': '#061423',
        'on-tertiary-container': '#0094a6',
        'inverse-on-surface': '#243141',
        'background': '#061423',
        'surface-container-lowest': '#020f1e',
        'inverse-surface': '#d6e4f9',
        'inverse-primary': '#476083',
        'surface-dim': '#061423',
        'on-error': '#690005',
        'primary-fixed-dim': '#afc8f0',
        'surface-container-high': '#1e2b3b',
        'on-primary': '#163152',
        'outline-variant': '#43474e',
        'on-background': '#d6e4f9',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        'space-grotesk': ['var(--font-space-grotesk)', 'sans-serif'],
        headline: ['var(--font-space-grotesk)', 'sans-serif'],
        display: ['var(--font-space-grotesk)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
